[2022-07-28 11:00:03,177] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-28T10:00:00+00:00 [queued]>
[2022-07-28 11:00:03,188] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-28T10:00:00+00:00 [queued]>
[2022-07-28 11:00:03,189] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 11:00:03,189] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 11:00:03,189] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 11:00:03,206] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-28 10:00:00+00:00
[2022-07-28 11:00:03,211] {standard_task_runner.py:52} INFO - Started process 3147 to run task
[2022-07-28 11:00:03,218] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-28T10:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpvmtsqaa9', '--error-file', '/tmp/tmprjwpvr3b']
[2022-07-28 11:00:03,219] {standard_task_runner.py:80} INFO - Job 47: Subtask is_api_available
[2022-07-28 11:00:03,342] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-28T10:00:00+00:00 [running]> on host 890323d6f4a0
[2022-07-28 11:00:03,449] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T10:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-28T10:00:00+00:00
[2022-07-28 11:00:03,450] {http.py:97} INFO - Poking: api/
[2022-07-28 11:00:03,461] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-28 11:00:03,463] {http.py:129} INFO - Sending 'GET' to url:  https://randomuser.me/api/
[2022-07-28 11:00:05,401] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-28 11:00:05,418] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220728T100000, start_date=20220728T110003, end_date=20220728T110005
[2022-07-28 11:00:05,439] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-28 11:00:05,483] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
