[2022-07-28 10:21:13,348] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-28T10:21:11.212618+00:00 [queued]>
[2022-07-28 10:21:13,359] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-28T10:21:11.212618+00:00 [queued]>
[2022-07-28 10:21:13,359] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 10:21:13,360] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 10:21:13,360] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 10:21:13,378] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-28 10:21:11.212618+00:00
[2022-07-28 10:21:13,383] {standard_task_runner.py:52} INFO - Started process 1298 to run task
[2022-07-28 10:21:13,386] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-28T10:21:11.212618+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp1t3zr2sf', '--error-file', '/tmp/tmplglxkqqn']
[2022-07-28 10:21:13,388] {standard_task_runner.py:80} INFO - Job 37: Subtask is_api_available
[2022-07-28 10:21:13,489] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-28T10:21:11.212618+00:00 [running]> on host 890323d6f4a0
[2022-07-28 10:21:13,579] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T10:21:11.212618+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-28T10:21:11.212618+00:00
[2022-07-28 10:21:13,580] {http.py:97} INFO - Poking: api/
[2022-07-28 10:21:13,589] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-28 10:21:13,591] {http.py:129} INFO - Sending 'GET' to url:  https://randomuser.me/api/
[2022-07-28 10:21:14,195] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-28 10:21:14,208] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220728T102111, start_date=20220728T102113, end_date=20220728T102114
[2022-07-28 10:21:14,241] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-28 10:21:14,291] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
