[2022-07-28 10:13:24,931] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-28T10:13:22.952035+00:00 [queued]>
[2022-07-28 10:13:24,946] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-28T10:13:22.952035+00:00 [queued]>
[2022-07-28 10:13:24,947] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 10:13:24,947] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 10:13:24,948] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 10:13:24,964] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-28 10:13:22.952035+00:00
[2022-07-28 10:13:25,043] {standard_task_runner.py:52} INFO - Started process 903 to run task
[2022-07-28 10:13:25,046] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-28T10:13:22.952035+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpell3qrv5', '--error-file', '/tmp/tmpso6iz__a']
[2022-07-28 10:13:25,047] {standard_task_runner.py:80} INFO - Job 32: Subtask is_api_available
[2022-07-28 10:13:25,102] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-28T10:13:22.952035+00:00 [running]> on host 890323d6f4a0
[2022-07-28 10:13:25,175] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T10:13:22.952035+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-28T10:13:22.952035+00:00
[2022-07-28 10:13:25,176] {http.py:97} INFO - Poking: api/
[2022-07-28 10:13:25,185] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-28 10:13:25,187] {http.py:129} INFO - Sending 'GET' to url:  https://randomuser.me/api/
[2022-07-28 10:13:27,649] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-28 10:13:27,661] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220728T101322, start_date=20220728T101324, end_date=20220728T101327
[2022-07-28 10:13:27,709] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-28 10:13:27,756] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
